### ISSUE TITLE
Grey page visible after some time of opening WhatsApp.

### ISSUE THREAD

**Issue by Vinit5893** [eneshecan/whatsapp-for-linux#347] opened 2023-10-07 13:02 UTC
**Description**
Whenever I launch WhatsApp it works fine for some time and then after a while, a grey screen is visible for no reason.
I have to click the refresh button in order to use it again. After sometime the bug again reverts the gray page.  
**Expected behavior**
The normal operation is expected

**Screenshots**
![Screenshot from 2023-10-07 18-24-41](https://github.com/eneshecan/whatsapp-for-linux/assets/90704540/0bca3be7-723a-44aa-8565-0eddc90a1490)

**Environment**
 - Distro - Ubuntu 22.04.3 LTS
 - Package - flatpak, snap , debian
 - Gnome version - 42.9

**Comment by kkchaudhary11** [comment] 2023-10-12 04:44
Same issue

- Ubuntu - 23.04
- Package - snap
- GNOME version - 44.3

**Comment by the-solipsist** [comment] 2023-10-20 06:47
Seems like a duplicate of #330.

**Closed** 2023-11-23 09:10 UTC
Labels: bug, duplicate
