### ISSUE TITLE
Preview for links not being generated

### ISSUE THREAD

**Issue by EkanshdeepGupta** [eneshecan/whatsapp-for-linux#210] opened 2022-07-03 22:29 UTC
**Description**
When sending a message containing a link, the preview generated for the link does not fetch any details about the linked webpage. When pasting a link in a chat from a phone or web.whatsapp.com, WhatsApp generates a preview for the url including a title and thumbnail. However, for links sent via whatsapp-for-linux, the preview only contains the url.

**To Reproduce**
1. Go to any chat.
2. Copy a link to a website in the chat
3. Wait a couple of seconds for the preview to be generated
4. The preview merely has the URL, not the title or thumbnail.

**Expected behavior**
The generated preview should have the title and thumbnail.

**Screenshots**
Preview generated by whatsapp-for-linux:
![Screenshot](https://user-images.githubusercontent.com/13527018/177059285-3cf67d5b-3fbf-4c8e-b0f4-bff99c5c8891.png)

Preview generated by WhatsApp on phone:
![Screenshot](https://user-images.githubusercontent.com/13527018/177059287-61b78a36-c73e-4a9a-bacb-c5789352d762.png)

**Environment**

 - Distro [ Fedora Linux 36 ]
 - Package [ Flatpak]
 - Desktop Environment or Window Manager [ Gnome 42.2 ]

**Comment by eneshecan** [comment] 2022-07-04 13:15
This is a duplicate of #201

**Closed** 2022-07-04 17:11 UTC
Labels: bug, duplicate, wontfix, upstream
