### ISSUE TITLE
App fails to start

### ISSUE THREAD

**Issue by thefamousnomo** [eneshecan/whatsapp-for-linux#189] opened 2022-04-05 08:32 UTC
fails to open with the following error

<13>Apr  5 09:28:19 whatsapp-for-linux[13783]: ** (whatsapp-for-linux:13707): ERROR **: 09:28:19.123: Unable to fork a new child process: Failed to execute child process “/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess” (No such file or directory)

this file does exist

 - Ubuntu 20.04
 - snap
 - Gnome

**Comment by jreus** [comment] 2022-04-05 08:58
Maybe the same error? Whatsapp for linux crashes on open. But was working a few days ago.
I'm running the appimage on KDE / Kubuntu
Crash report / stack trace is attached!
[whatsapp-crash.txt](https://github.com/eneshecan/whatsapp-for-linux/files/8416553/whatsapp-crash.txt)

**Comment by KevinEfrogg** [comment] 2022-04-06 08:17
I think i have the same issue since friday : 

<13>Apr  6 10:13:25 whatsapp-for-linux[60319]: 
<13>Apr  6 10:13:25 whatsapp-for-linux[60319]: (whatsapp-for-linux:60247): Gtk-WARNING **: 10:13:25.880: Theme parsing error: gtk.css:1428:23: 'font-feature-settings' is not a valid property name
<13>Apr  6 10:13:25 whatsapp-for-linux[60319]: 
<13>Apr  6 10:13:25 whatsapp-for-linux[60319]: (whatsapp-for-linux:60247): Gtk-WARNING **: 10:13:25.885: Theme parsing error: gtk.css:3318:25: 'font-feature-settings' is not a valid property name
<13>Apr  6 10:13:25 whatsapp-for-linux[60319]: 
<13>Apr  6 10:13:25 whatsapp-for-linux[60319]: (whatsapp-for-linux:60247): Gtk-WARNING **: 10:13:25.885: Theme parsing error: gtk.css:3780:23: 'font-feature-settings' is not a valid property name
<13>Apr  6 10:13:26 whatsapp-for-linux[60319]: 
<13>Apr  6 10:13:26 whatsapp-for-linux[60319]: ** (whatsapp-for-linux:60247): WARNING **: 10:13:26.287: Could not open /sys/class/dmi/id/chassis_type: Failed to open file “/sys/class/dmi/id/chassis_type”: Permission denied
<13>Apr  6 10:13:26 whatsapp-for-linux[60319]: 
<13>Apr  6 10:13:26 whatsapp-for-linux[60319]: ** (whatsapp-for-linux:60247): WARNING **: 10:13:26.287: Could not open /sys/firmware/acpi/pm_profile: Failed to open file “/sys/firmware/acpi/pm_profile”: Permission denied
<13>Apr  6 10:13:26 whatsapp-for-linux[60319]: 
<13>Apr  6 10:13:26 whatsapp-for-linux[60319]: ** (whatsapp-for-linux:60247): ERROR **: 10:13:26.291: Unable to fork a new child process: Failed to execute child process “/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess” (No such file or directory)

**Comment by eneshecan** [comment] 2022-04-06 12:48
For the appimage, the issue is #160. Other than that, I think this is a snap issue.

**Comment by tristobal** [comment] 2022-04-06 22:07
Same error here
```
<13>Apr  6 17:44:27 whatsapp-for-linux[24077]: 
<13>Apr  6 17:44:27 whatsapp-for-linux[24077]: (whatsapp-for-linux:24010): Gtk-WARNING **: 17:44:27.550: Theme parsing error: gtk.css:1418:23: 'font-feature-settings' is not a valid property name
<13>Apr  6 17:44:27 whatsapp-for-linux[24077]: 
<13>Apr  6 17:44:27 whatsapp-for-linux[24077]: (whatsapp-for-linux:24010): Gtk-WARNING **: 17:44:27.552: Theme parsing error: gtk.css:3295:25: 'font-feature-settings' is not a valid property name
<13>Apr  6 17:44:27 whatsapp-for-linux[24077]: 
<13>Apr  6 17:44:27 whatsapp-for-linux[24077]: (whatsapp-for-linux:24010): Gtk-WARNING **: 17:44:27.553: Theme parsing error: gtk.css:3757:23: 'font-feature-settings' is not a valid property name
<13>Apr  6 17:44:27 whatsapp-for-linux[24077]: 
<13>Apr  6 17:44:27 whatsapp-for-linux[24077]: ** (whatsapp-for-linux:24010): WARNING **: 17:44:27.717: Could not open /etc/machine-info: Failed to open file “/etc/machine-info”: Permission denied
<13>Apr  6 17:44:27 whatsapp-for-linux[24077]: 
<13>Apr  6 17:44:27 whatsapp-for-linux[24077]: ** (whatsapp-for-linux:24010): WARNING **: 17:44:27.717: Could not open /sys/class/dmi/id/chassis_type: Failed to open file “/sys/class/dmi/id/chassis_type”: Permission denied
<13>Apr  6 17:44:27 whatsapp-for-linux[24077]: 
<13>Apr  6 17:44:27 whatsapp-for-linux[24077]: ** (whatsapp-for-linux:24010): WARNING **: 17:44:27.717: Could not open /sys/firmware/acpi/pm_profile: Failed to open file “/sys/firmware/acpi/pm_profile”: Permission denied
<13>Apr  6 17:44:27 whatsapp-for-linux[24077]: 
<13>Apr  6 17:44:27 whatsapp-for-linux[24077]: ** (whatsapp-for-linux:24010): ERROR **: 17:44:27.719: Unable to fork a new child process: Failed to execute child process “/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess” (No such file or directory)
[1]    24010 trace trap (core dumped)  whatsapp-for-linux
```

* Manjaro
* Gnome
* Snap

**Comment by thefamousnomo** [comment] 2022-04-07 10:43
yeah, same here... working again...

**Comment by tristobal** [comment] 2022-04-07 13:17
Same here: Magic! Five star, excellent service!

**Comment by eneshecan** [comment] 2022-04-07 15:58
Glad to hear that. Well, we didn't do anything, it must be something which is fixed by snap I suppose...

**Closed** 2022-04-09 10:42 UTC
Labels: bug, snap

**Comment by jaum20** [comment] 2022-06-08 13:45
I still have this problem: 

```
whatsapp-for-linux 
<13>Jun  8 10:44:14 whatsapp-for-linux[89919]: Gtk-Message: 10:44:14.884: Failed to load module "xapp-gtk3-module"
<13>Jun  8 10:44:15 whatsapp-for-linux[89919]: 
<13>Jun  8 10:44:15 whatsapp-for-linux[89919]: ** (whatsapp-for-linux:89844): WARNING **: 10:44:15.037: Could not open /sys/class/dmi/id/chassis_type: Failed to open file “/sys/class/dmi/id/chassis_type”: Permission denied
<13>Jun  8 10:44:15 whatsapp-for-linux[89919]: 
<13>Jun  8 10:44:15 whatsapp-for-linux[89919]: ** (whatsapp-for-linux:89844): WARNING **: 10:44:15.037: Could not open /sys/firmware/acpi/pm_profile: Failed to open file “/sys/firmware/acpi/pm_profile”: Permission denied
<13>Jun  8 10:44:15 whatsapp-for-linux[89919]: 
<13>Jun  8 10:44:15 whatsapp-for-linux[89919]: ** (whatsapp-for-linux:89844): ERROR **: 10:44:15.040: Unable to fork a new child process: Failed to execute child process “/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess” (No such file or directory)
[1]    89844 trace trap  whatsapp-for-linux
```
