### ISSUE TITLE
Keeps freezing/spinning the CPU

### ISSUE THREAD

**Issue by atleta** [eneshecan/whatsapp-for-linux#224] opened 2022-09-01 14:30 UTC
**Description**
It keeps freezing (spinning the CPU @ 100%). It seems to happen when I want to download and/or display a specific image in a conversation. The picture is pretty small (it says it's
 340k) and it's somewhat up in my message history (about 2 weeks old now).

**To Reproduce**
1. Go to the message view, scroll back ~100 messages
2. Click on a picture
3. UI freezes, CPU usage goes to 100%, the app displays a popup saying 'whatsapp for linux not responding. Would you like to reload?'. Reloading solves the issue, but it will happen again if I try to open the same image. (The image is valid, not bogus, the app was able to open it a few times before.)

**Expected behavior**

**Screenshots**
![Error popup](https://user-images.githubusercontent.com/6267837/187939096-63018141-56cf-4d3d-a2cd-dfc8f4bd07c3.png)

**Environment**
 - Distro Ubuntu
 - Package deb
 - Desktop Environment or Window Manager Gnome
 - Versions: Ubuntu 20.04, Gnome 3.36, whatsapp for linux 1.4.6

**Comment by eneshecan** [comment] 2022-09-01 14:44
Try to set hardware acceleration to `Never` in Preferences window.

**Comment by ndias** [comment] 2022-09-01 20:15
I have the same problem, and have also change the hardware acceleration to "Never", but the startup of the application is very  slow, sometimes takes 5 minutos to display anything

**Comment by enricorox** [comment] 2022-09-07 09:44
> Try setting hardware acceleration to `Never` in Preferences window.

Done but it keeps using ~20% of CPU while idle

**Comment by eneshecan** [comment] 2022-09-21 21:32
Cannot find a solution for this. Probably an upstream issue as I was able to reproduce with Epiphany as well.

**Comment by eneshecan** [comment] 2022-09-26 10:45
The issue is gone for me on Arch Linux. Please try the latest release and let me know.

**Comment by ndias** [comment] 2022-09-26 12:58
Yes, in Fedora is again usable thanks

**Comment by eneshecan** [comment] 2022-09-26 16:32
@atleta Please close this if you don't experience anymore with the latest release.

**Comment by atleta** [comment] 2022-09-26 18:11
@eneshecan I was not aware that you've released a fix, which you apparently did 9 hours ago. But turning HW acceleration on again works even with the old (1.4.6) version now as well as with 1.4.7.

**Closed** 2022-09-26 18:12 UTC
Labels: bug
