### ISSUE TITLE
Cannot paste clipboard text from the program xclip

### ISSUE THREAD

**Issue by Ghibranalj** [eneshecan/whatsapp-for-linux#159] opened 2022-01-19 21:39 UTC
**Description**
Cannot paste a text that is copied fron the program  [xclip](https://github.com/astrand/xclip). but 'paste as plain' text works

**To Reproduce**
1. Copy the content of a file to clipboard with the command `xclip -sel c < text.txt`
2. Paste it to whatsapp-for-linux to any input field 
3. No text shows up

**Expected behavior**
The selected text gets pasted 

**Video demonstration**
[the video demonstration](https://emalm.com/?v=axkR7)

**Environment**
 - Arch Linux
 - aur (yay)
 - Cinnamon 5.0.7
 - kernel 5.15.10-arch1-1

**Comment by Ghibranalj** [comment] 2022-03-02 10:47
I use gnome on x11 not on wayland

**Comment by eneshecan** [comment] 2022-03-04 16:19
I've tested this on both X11 and Wayland and couldn't reproduce. Could you please check again?

**Comment by eneshecan** [comment] 2022-03-04 16:52
`xclip -selection clipboard -t text/plain < test.txt`
It works when you select the target as plain text. Actually, this explains the issue. I believe `xclip` doesn't copy things as plain text by default and that's why it works when you click `Paste as Plain Text` and GTK framework have both of those paste options for convenience I guess compared to other frameworks.

**Comment by eneshecan** [comment] 2022-03-06 00:06
Okay, I think I understand now;

If you try to paste a rich text, it depends on the application/website to accept this input. In this case, Whatsapp Web doesn't allow this.

So, either you should use `Paste as a Plain Text / Ctrl+Shift+V` or copy your text in a plain format.

Since this is expected behavior, I will close this if no one has an objection.

**Comment by Sadi58** [comment] 2022-03-13 10:23
Thanks! Replacing the command `xclip -i -selection clipboard` with `xclip -i -selection clipboard -t text/plain` in a couple of my scripts, or/and - in some cases - using **Ctr+Shift+V** instead of _Ctrl+V_ works great for me.

**Closed** 2022-03-30 10:55 UTC
Labels: bug, good first issue
