### ISSUE TITLE
Paste from the clipboard image from screen shot

### ISSUE THREAD

**Issue by jreo** [eneshecan/whatsapp-for-linux#117] opened 2021-05-27 11:26 UTC
Hi,

Is not possible to paste from the clipboard when create screen shot.

Thank you.

**Comment by tom-james-watson** [comment] 2021-05-27 14:38
Duplicate of https://github.com/eneshecan/whatsapp-for-linux/issues/79

**Closed** 2021-06-03 21:22 UTC
Labels: duplicate, enhancement
