### ISSUE TITLE
Error message when opening Whatsapp app for Linux

### ISSUE THREAD

**Issue by serial02** [eneshecan/whatsapp-for-linux#282] opened 2023-04-07 18:23 UTC
Hello whatsapp-for-linux team

Congratulations to the whole team for the excellent work on this app. 
 Lightweight, beautiful and functional.

**Description**

When running the flatpak command and opening the application through the terminal, the following error messages appear below.
 If it is something pertinent, please provide the correction.  If not, please disregard.

```
flatpak run com.github.eneshecan.WhatsAppForLinux
F: Not sharing "/dev/log" with sandbox: Path "/dev" is reserved by Flatpak
Gtk-Message: 14:37:31.339: Failed to load module "canberra-gtk-module"
Gtk-Message: 14:37:32.005: Failed to load module "canberra-gtk-module"
Gtk-Message: 14:37:32.058: Failed to load module "canberra-gtk-module"
logger: soquete /dev/log: Missing file or directory
```

When receiving text messages it is not triggering the sound of receiving messages.
 Voicemail works normally.
Note: see that in the image below the sound icon is activated.

Language translation is almost perfect with the exception of app settings and preferences,as shown in the picture below.

![Capturar_select-area_20230407151305](https://user-images.githubusercontent.com/32621790/230657899-ed11a80a-2403-43ce-ab6d-1723f22a2e34.png)

**Expected behavior**

translation improvements, message receipt sound works

**Screenshots**

Already sent in the description above..

**Environment**
 - Distro [e.g. Ubuntu, Arch Linux]
 - Package [e.g. snap, debian]
 - Desktop Environment or Window Manager [e.g. Gnome, i3wm]

Attached screenshot of desktop description:

![Capturar_select-area_20230407102217](https://user-images.githubusercontent.com/32621790/230658443-bb0ccaa3-9240-47b9-b571-3ff55ddb989a.png)

Thank you all and much success to the whole team

**Comment by eneshecan** [comment] 2023-04-09 21:23
Hi @serial02, thank you for reporting!

- I believe that the error message about the notification is harmless. In order to get the notifications you need to allow them by clicking the warning on the top left or enabling `Allow Permissions` in the Web section of the preferences window and restarting the app.
- Translations of the app and webpage are different. In your case, I assume that we don't have the corresponding translations. We can make sure if you could paste here the output of `localectl` command. We have `pt-br` translations as you can see [here](https://poeditor.com/join/project/jMGkxVn3vN). You can either contribute if you want to see the translations regarding your language. Otherwise, maybe we can rename `pt-br` to `pt` if that's convenient for the Portuguese folks which I can't tell...

**Comment by serial02** [comment] 2023-04-10 17:08
> * I believe the error message on the notification is harmless.  To receive the notifications, you need to enable them by clicking the notice in the top left corner or enabling `Allow Permissions` in the Web section of the preferences window and restarting the application.

Hello @eneshecan 

As for the pop-up messages received, they appear normally in the gnome window in the center of the screen at the top normally.

Now the issue at hand is the sound receipt of the (received message) not working.

> * Application and web page translations are different.  In your case, I assume we don't have the corresponding translations.  We can be sure if you paste the output of the `localectl` command here.  We have `en-us` translations as you can see [here](https://poeditor.com/join/project/jMGkxVn3vN) .  You can contribute if you want to see the translations referring to your language.  If not, maybe we could rename `pt-br` to `pt` if that's convenient for the Portuguese, which I can't say...

As for the translations, I will see what I can contribute when possible.

 Thank you very much for your attention and much success to all!

**Comment by eneshecan** [comment] 2023-05-17 08:36
And I cannot reproduce the error messages with flatpak on my Debian VM. Probably, those are harmless as we don't depend on the canberra-gtk-module. Closing this issue now, please open a new one or advise the existing ones about the other specific issues.

**Closed by eneshecan** 2023-05-17 08:36 UTC
Labels: bug
