### ISSUE TITLE
Does not work with hardware acceleration + does not persist preferences

### ISSUE THREAD

**Issue by dimisjim** [eneshecan/whatsapp-for-linux#216] opened 2022-07-23 12:52 UTC
**Description**
App does not work with hardware acceleration.

**To Reproduce**
1. opening the app leads to $(see screenshot)

**Expected behavior**
The app to open without changing the preferences

It only works if one toggles the hardware acceleration to "Never".

But then this leads to the trackpad not being able to scroll up and down + it also doesn't persist the preferences that make it to work even in this limited way.

**Screenshots**
![image](https://user-images.githubusercontent.com/6890249/180605626-508384a8-e9b0-429c-9446-b155f0360685.png)

**Environment**
 - Ubuntu 22.04
 - https://github.com/eneshecan/whatsapp-for-linux/releases/download/v1.4.5/whatsapp-for-linux_1.4.5_amd64.deb
 - Gnome 42.2 on Wayland
 - Lenovo T580

**Comment by pwepwe973** [comment] 2022-07-27 02:40
hello 
same problem

sorry for my english i am french

**Comment by eneshecan** [comment] 2022-07-27 08:16
Could you please check if the app crashes on closing the application? Because we write the whole config to the file upon exiting the app.

**Comment by dimisjim** [comment] 2022-07-27 09:54
@eneshecan The app opens "half-way". Without the hardware acceleration toggle, it stays to this stale screen in the screenshot shown above. I am not sure what you mean by "crash", I didn't mention any, just the faulty behavior with the hw acceleration I mentioned above and the non-persisting settings. most likely there's a crash yeah, but can't share it currently as I don't have the laptop at hand until at leats the next month or so.

**Comment by eneshecan** [comment] 2022-07-27 14:07
Yeah, I am asking because not being able to persist preferences might be related to a crash on exit. About the app not being able to render properly, I cannot say anything atm since I cannot reproduce it. It would be nice to see some logs.

**Comment by dimisjim** [comment] 2022-07-28 11:24
Can't post the logs as of now (see laptop in a month comment above)

but I can confirm that it does work without any issues on a newer t16 laptop, with same ubuntu and wayland versions.

so it's most likely a problem with the compatibility of the hw on the T580. It could be related to issues such as this: https://bugs.launchpad.net/bugs/1958191 and integrated Intel graphics drivers of that generation.

**Comment by eneshecan** [comment] 2022-09-26 16:31
Does this issue still persists? @dimisjim

**Comment by dimisjim** [comment] 2022-09-26 16:33
@eneshecan haven't checked tbh, have switched back to https://gitlab.com/zerkc/whatsdesk/ which worked back then without issues.

**Closed** 2022-09-26 16:36 UTC
Labels: bug
