### ISSUE TITLE
Spell check does not work

### ISSUE THREAD

**Issue by dimisjim** [eneshecan/whatsapp-for-linux#215] opened 2022-07-23 12:22 UTC
**Description**
Tried installing `aspell-en` too, as suggested in https://github.com/eneshecan/whatsapp-for-linux/issues/92.  See screenshot below.

Also, does the spell check supposed to work for multiple languages at the same time? For example, I also have `aspell-el` installed.

**Expected behavior**
spell check works

**Screenshots**
![image](https://user-images.githubusercontent.com/6890249/180604422-94d79496-8334-4d82-b4f9-4181db1b67aa.png)

![image](https://user-images.githubusercontent.com/6890249/180604678-038893b8-5337-46b9-9f0c-a7b997af6d28.png)

**Environment**
 - Ubuntu 22.04
 - https://github.com/eneshecan/whatsapp-for-linux/releases/download/v1.4.5/whatsapp-for-linux_1.4.5_amd64.deb
 - Gnome 42.2 with X11

**Comment by eneshecan** [comment] 2022-07-30 22:19
Hi @dimisjim. It currently selects the system language and should work if the corresponding dictionary is installed but I have some plans to make it selectable in the future.... I just tested on my Debian machine with our deb package and couldn't reproduce.

**Comment by dimisjim** [comment] 2022-07-31 07:42
hmm it could be then an Ubuntu 22 specific issue. Thanks for checking

**Comment by eneshecan** [comment] 2022-09-26 16:30
Closing this then due to being not reproducible.

**Closed by eneshecan** 2022-09-26 16:30 UTC
Labels: bug, good first issue
